[project]
name = "design-bench"
version = "0.1.0"
description = "Please input description"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "datasets[vision]>=2.0.0,<4.0.0",
    "gdown>=5.2.0",
    "tenacity>=9.1.2",
]

