[project]
name = "object-removal-alpha"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shunsuke KITADA", email = "shunsuke.kitada.0831@gmail.com" },
]
requires-python = ">=3.10"
dependencies = ["datasets[vision]>=2.0.0,<4.0.0"]
